/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linkedList;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        LinkedList<Integer> age = new LinkedList<Integer>();
////        Integer value = 5;
        age.insertValue(5);
        age.insertValue(50);
//
        System.out.println(age.includesValue(5));
        System.out.println(age.includesValue(520));
//
        System.out.println(age.tostring());
//
        System.out.println("AYA");

    }
}
