/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());


        int[] arr = new int[]{8, 4, 23, 42, 15, 16};
        insertionSort(arr);
        System.out.println(" ");
        System.out.print("Insertion Sort: ");
        print(arr);
        System.out.println(" ");

    }


    public static int[] insertionSort(int[] arr)
    {
        int length = arr.length;

        for (int i = 1; i < length ; i++) {
            int j = i - 1;
            int temp = arr[i];

            while (j >= 0 && temp < arr[j]) {
                arr[j + 1] = arr[j];
                j = j - 1;
            }

            arr[j + 1] = temp;
        }
        return arr;
    }


    public static int[] print(int[] arr) {

        for (int i = 0; i < arr.length; i++) {
            System.out.print(arr[i] + " ");
        }
        return arr;
    }
}
