/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package class06;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        LinkedList<Integer> age = new LinkedList<Integer>();
////        Integer value = 5;

        age.insertValue(1);
        age.insertValue(2);
        age.insertValue(3);

        age.append(5);
        age.append(50);
        age.append(66);

        age.insertAfter(5,100);
        age.insertBefore(100 , 99);
//
        System.out.println(age.toString());
//
    }
}
