import data.BTNode;
import structure.BinaryTree;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());




        BinaryTree<Integer> binaryTreeOne = new BinaryTree<>(new BTNode(7));
        BTNode node1 = new BTNode(20);
        BTNode node2 = new BTNode(12);
        BTNode node3 = new BTNode(5);
        BTNode node5 = new BTNode(16);
        BTNode node4 = new BTNode(3);
//        binaryTreeOne.getRoot().getRight() = node4;
//        binaryTreeOne.getRoot().getLeft() = node3;

        BinaryTree<Integer> binaryTreeTwo = new BinaryTree<>(new BTNode(47));
        BTNode node6 = new BTNode(5);
        BTNode node7 = new BTNode(16);
        BTNode node8 = new BTNode(7);
        BTNode node9 = new BTNode(58);
        BTNode node10 = new BTNode(3);
//        binaryTreeTwo.getRoot().getRight() = node10;
//        binaryTreeTwo.getRoot().getLeft() = node8;

//
//        System.out.println(tr(binaryTreeOne, binaryTreeTwo));


    }



}
