import structure.HashMap;

import java.util.HashSet;
import java.util.Set;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {

        System.out.println(new App().getGreeting());

        HashMap<String, String> hashMap = new HashMap<>();
        hashMap.set("JAVA", "JAVA");
        hashMap.set("Amman", "Amman");
        hashMap.set("Jordan", "Jordan");
        hashMap.set("J", "J");
        hashMap.set("Bob", "Bob");
        hashMap.set("Carl", "Carl");

        System.out.println("*******************************");
        System.out.println(hashMap.contain("J"));
        System.out.println(hashMap.contain("Aya"));

        System.out.println("============");
        System.out.println(hashMap.getKeys());
        System.out.println(hashMap.get("Carl"));

        System.out.println(";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;");

        System.out.println(hashMap.isUniqueChars("The quick brown fox jumps over the lazy dog"));
        System.out.println(hashMap.isUniqueChars("I love cats"));
        System.out.println(hashMap.isUniqueChars("Donald the duck"));


        System.out.println("---------------------------CC31-----------------------------------)");

//
        System.out.println("kkkk");
        System.out.println(hashMap.repeatedWord("The quick brown fox jumps over quick the lazy dog quick"));

        System.out.println(hashMap.repeatedWord("It was a queer, sultry summer, the summer they electrocuted the Rosenbergs, and I didn’t know what I was doing in New York..."));

        System.out.println(hashMap.repeatedWord("Once upon a time, there was a brave princess who..."));

        System.out.println(hashMap.repeatedWord("It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness, it was the epoch of belief, it was the epoch of incredulity, it was the season of Light, it was the season of Darkness, it was the spring of hope, it was the winter of despair, we had everything before us, we had nothing before us, we were all going direct to Heaven, we were all going direct the other way – in short, the period was so far like the present period, that some of its noisiest authorities insisted on its being received, for good or for evil, in the superlative degree of comparison only..."));
    }

}
