/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import org.junit.jupiter.api.DisplayName;

import java.util.Arrays;

import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }

    @Test
    @DisplayName("Empty Array QuickSort")
    public void emptyMergeSortArray() {
        int[] arr = new int[]{};
        App.QuickSort(arr,0, arr.length-1);
        int[] expected = {};

        assertEquals(Arrays.toString(expected), Arrays.toString(arr));
    }


    @Test
    @DisplayName("QuickSort Method")
    public void mergeSort() {
        int[] arr = {8,4,23,42,16,15};
        App.QuickSort(arr,0, arr.length-1);
        int[] expected = {4, 8, 15, 16, 23, 42};

        assertEquals(Arrays.toString(expected), Arrays.toString(arr));

    }

}
