/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import structure.HashMap;

import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }




    @Test
    public void SettingValuesKeys() {

            HashMap<String, String> hashMap = new HashMap<>();
            hashMap.set("JAVA", "JAVA");
            hashMap.set("Amman", "Amman");
            hashMap.set("Jordan", "Jordan");
            hashMap.set("J", "J");
            hashMap.set("Bob", "Bob");
            hashMap.set("Carl", "Carl");

            int result = 6;
            int expected = hashMap.getSize();

            assertEquals(expected,result);

    }


    @Test
    public void returnKeys() {

        HashMap<String, String> hashMap = new HashMap<>();
        hashMap.set("JAVA", "JAVA");
        hashMap.set("Amman", "Amman");
        hashMap.set("Jordan", "Jordan");
        hashMap.set("J", "J");
        hashMap.set("Bob", "Bob");
        hashMap.set("Carl", "Carl");

        String result = "[Jordan, Amman, JAVA, J, Bob, Carl]" ;
        String expected = hashMap.getKeys().toString();

        assertEquals(expected,result);

    }

    @Test
    public void returnNullKey() {

        HashMap<String, String> hashMap = new HashMap<>();
        hashMap.set("JAVA", "JAVA");
        hashMap.set("Amman", "Amman");
        hashMap.set("Jordan", "Jordan");
        hashMap.set("J", "J");
        hashMap.set("Bob", "Bob");
        hashMap.set("Carl", "Carl");

//        String result = null ;
        String expected = hashMap.get("aya");

        assertEquals(expected,null);

    }



    @Test
    public void containKeys() {

        HashMap<String, String> hashMap = new HashMap<>();
        hashMap.set("JAVA", "JAVA");
        hashMap.set("Amman", "Amman");
        hashMap.set("Jordan", "Jordan");
        hashMap.set("J", "J");
        hashMap.set("Bob", "Bob");
        hashMap.set("Carl", "Carl");

        boolean result = true ;
        boolean expected = hashMap.contain("JAVA");

        assertEquals(expected,result);

    }



    @Test
    public void containNoKeys() {

        HashMap<String, String> hashMap = new HashMap<>();
        hashMap.set("JAVA", "JAVA");
        hashMap.set("Amman", "Amman");
        hashMap.set("Jordan", "Jordan");
        hashMap.set("J", "J");
        hashMap.set("Bob", "Bob");
        hashMap.set("Carl", "Carl");

        boolean result = false ;
        boolean expected = hashMap.contain("aya");

        assertEquals(expected,result);

    }


    @Test
    public void hashKeys() {

        HashMap<String, String> hashMap = new HashMap<>();
        hashMap.set("JAVA", "JAVA");

        int result = 187265416;
        int expected = hashMap.hashCode();

        assertEquals(expected,result);

    }
}
