/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package class7;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());


        LinkedList<Integer> list = new LinkedList<Integer>();
        list.insert(5);
        list.insert(10);
        list.insert(12);
        list.insert(99);

        System.out.println("LIST = "+ list);

        System.out.println("----------------------------------------------");

        System.out.print("The kth From End ==> ");
        System.out.println(list.kthFromEnd(1));

        System.out.println("----------------------------------------------");
        System.out.println(list.toString());

    }
}
