/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import org.junit.jupiter.api.DisplayName;

import java.util.Arrays;

import static org.junit.Assert.*;

public class AppTest {
    @Test
    public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }

    @Test
    @DisplayName("Empty Array InsertionSort")
    public void emptyInsertionArray() {
        int[] arr = new int[]{};
        App.insertionSort(arr);
        int[] expected = {};

        assertEquals(Arrays.toString(expected), Arrays.toString(arr));
    }

    @Test
    @DisplayName("Insertion Array")
    public void insertionArray() {
        int[] arr = new int[]{8, 4, 23, 42, 15, 16};
        App.insertionSort(arr);
        int[] expected = {4, 8, 15, 16, 23, 42};

        assertEquals(Arrays.toString(expected), Arrays.toString(arr));
    }



    @Test
    @DisplayName("Empty Array MergeSort")
    public void emptyMergeSortArray() {
        int[] arr = new int[]{};
        App.mergeSort(arr);
        int[] expected = {};

        assertEquals(Arrays.toString(expected), Arrays.toString(arr));
    }


    @Test
    @DisplayName("Merge Sort")
    public void mergeSort() {
        int[] arr = new int[]{12, 11, 13, 5, 6, 7};
        App.mergeSort(arr);
        int[] expected = {5, 6, 7, 11, 12, 13};

        assertEquals(Arrays.toString(expected), Arrays.toString(arr));

    }
}