/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {

        System.out.println(new App().getGreeting());





                Graph graph = new Graph();

                graph.addVertex("A");
                graph.addVertex("B");
                graph.addVertex("C");

                System.out.println("------------------------------------------------------------------------");
                System.out.println(graph.printGraph());




                graph.addEdges("A","B",1);
                graph.addEdges("B","C",2);
                graph.addEdges("A","C",3);

                System.out.println("------------------------------------------------------------------------");
                System.out.println(graph.printGraph());






                System.out.println("----------------------------------------------------------------------");
                System.out.println(graph.getVertices());



                System.out.println("-----------------------------------------------------------------------");
                System.out.println(graph.getNeighbors());



                System.out.println("-----------------------------------------------------------------------");
                System.out.println(graph.getSize());


    }
        }

