/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {

        System.out.println(new App().getGreeting());


        Graph graph = new Graph();
//        Pandora, Arendelle, Metroville, Monstroplolis, Narnia, Naboo

        graph.addVertex("Pandora");
        graph.addVertex("Arendelle");
        graph.addVertex("Metroville");
        graph.addVertex("Monstroplolis");
        graph.addVertex("Narnia");
        graph.addVertex("Naboo");


        System.out.println("------------------------------------------------------------------------");
        System.out.println(graph.printGraph());


        graph.addEdges("Pandora", "Arendelle", 1);
        graph.addEdges("Arendelle", "Metroville", 2);
        graph.addEdges("Arendelle", "Monstroplolis", 3);
        graph.addEdges("Metroville", "Narnia", 3);
        graph.addEdges("Metroville", "Naboo", 3);
        graph.addEdges("Monstroplolis", "Naboo", 3);

        System.out.println("------------------------------------------------------------------------");
        System.out.println(graph.printGraph());


        System.out.println("----------------------------------------------------------------------");
        System.out.println(graph.getVertices());


        System.out.println("-----------------------------------------------------------------------");
        System.out.println(graph.getNeighbors());


        System.out.println("-----------------------------------------------------------------------");
        System.out.println(graph.getSize());


        System.out.println("---------- Code Challenge 36 -------------");
        System.out.println(graph.bfs("Pandora"));


    }
}
